name: eventflow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get:
  google_fonts:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  fluttertoast:
  image_picker:
  firebase_storage:
  dotted_border:
  getwidget:
  google_sign_in:
  intl:
  percent_indicator:
  google_nav_bar:
  auto_size_text:
  flutter_stripe:
  http:
  syncfusion_flutter_pdf:
  path_provider:
  open_file:
  screenshot:
  share_plus:
  firebase_messaging:
  firebase_analytics:
  flutter_local_notifications:
  flutter_datetime_picker:
  badges:
  status_bar_control:
  scroll_to_index:
  flutter_rating_bar:
  animated_background:
  gradient_widgets:
  flutter_email_sender:
  gap:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


